CREATE DATABASE ecommerce;

CREATE TABLE users (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  email varchar(50) UNIQUE NOT NULL,
  password varchar(128) NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE products (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name varchar(50) NOT NULL,
  category_id integer,
  description text,
  unit_price decimal(10, 2) NOT NULL,
  quantity_left integer NOT NULL
);

CREATE TABLE cart (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  total_value decimal(10, 2)
);

CREATE TABLE orders (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id),
  total_value decimal(10, 2) NOT NULL,
  status varchar(20) NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE order_items (
	order_id integer REFERENCES orders(id) ON DELETE CASCADE,
  product_id integer REFERENCES products(id) ON DELETE CASCADE,
  product_quantity integer NOT NULL,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE cart_items (
	cart_id integer REFERENCES cart(id),
  product_id integer REFERENCES products(id),
  product_quantity integer NOT NULL,
  PRIMARY KEY (cart_id, product_id)
);