CREATE DATABASE ecommerce;

CREATE TABLE users (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  email varchar(50) UNIQUE NOT NULL,
  password varchar(128) NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE subcategories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcategory_name varchar(30) NOT NULL
);

CREATE TABLE products (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name varchar(50) NOT NULL,
  main_category_id integer REFERENCES categories(id),
	sub_category_id integer REFERENCES subcategories(id),
  small_description text NOT NULL,
  main_description text NOT NULL,
  unit_price decimal(10, 2) NOT NULL,
  reviews_score decimal(10, 2),
  reviews_quantity integer,
  quantity_left integer NOT NULL
);

CREATE TABLE cart (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  total_value decimal(10, 2)
);

CREATE TABLE orders (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id),
  total_value decimal(10, 2) NOT NULL,
  status varchar(20) NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE order_items (
	order_id integer REFERENCES orders(id) ON DELETE CASCADE,
  product_id integer REFERENCES products(id) ON DELETE CASCADE,
  product_quantity integer NOT NULL,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE cart_items (
	cart_id integer REFERENCES cart(id),
  product_id integer REFERENCES products(id),
  product_quantity integer NOT NULL,
  PRIMARY KEY (cart_id, product_id)
);

CREATE TABLE colors (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(30) NOT NULL,
  code varchar(10) NOT NULL,
);

CREATE TABLE product_colors (
	product_id integer REFERENCES products(id),
  color_id integer REFERENCES colors(id),
  PRIMARY KEY (product_id, color_id)
);

CREATE TABLE product_features (
	product_id integer REFERENCES products(id),
  product_feature text NOT NULL,
  PRIMARY KEY (product_id, product_feature)
);

CREATE TABLE product_specifications (
	product_id integer REFERENCES products(id),
  spec_name varchar(30) NOT NULL,
  spec_content text NOT NULL,
  PRIMARY KEY (product_id, spec_name)
);

CREATE TABLE product_highlights (
	product_id integer REFERENCES products(id),
  title varchar(30) NOT NULL,
  content text NOT NULL,
  img_url text NOT NULL,
  PRIMARY KEY (product_id, img_url)
);